services:
  # floci is a replacement for localstack. It emulates AWS resources (sqs, sns, s3 etc) for local development
  # See: https://floci.io for more details
  floci:
    image: hectorvent/floci:latest-aws
    ports:
      - '4566:4566'
    env_file:
      - 'compose/aws.env'
    environment:
      FLOCI_DEFAULT_REGION: eu-west-2
    volumes:
      - ./compose/floci/start.d:/etc/floci/init/start.d:ro
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    networks:
      - cdp-tenant

  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: water_availability
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d water_availability']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cdp-tenant

  ################################################################################

  water-availability-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      POSTGRES_ENABLED: true
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: water_availability
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSL_REJECT_UNAUTHORIZED: false
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant

volumes:
  postgres-data:
